import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
import os
os.environ['CUDA_VISIBLE_DEVICES']=" "
os.environ['OMP_NUM_THREADS']="20"
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.threading.set_inter_op_parallelism_threads(1)


model = tf.keras.models.load_model('/media/guojunhao/DAB28C93B28C7633/linux_data2/voronoi/saved_model/mix.ver1.0')

# Check its architecture
# model.summary()

predict_data = pd.read_csv("100.csv")
p_features = predict_data.iloc[:, 0:40] # pay attention to the dataset! If generated by del-last, then 1:31; else, 0:30
p_F = tf.constant(p_features.values)
p_F1 = tf.reshape(p_F, (-1, 10, 4, 1))

prediction = model.predict(p_F1)
y_test_pred = np.argmax(prediction, axis=1)
y_test_output = y_test_pred.reshape(-1, 1)
pd.DataFrame(y_test_output).to_csv('150result')
